finalize directory
shyaler/azure-storage-azcopy pull request #15
Opened 2023-04-13 08:41 UTC by shyaler

While enumerating directory -> Adding the directory after adding all of its children +
markering the directory with folder end marker - to trigger finalize directory proccess.
In the Finalize proccess - add support to target compare mode.

please notice - this changes cause sync to work if nothing was changed in the source and the target.

2023-04-16 05:55 UTC, aymanjarrousms commented on cmd/syncComparator.go
> +	isTargetCompare := f.cfdMode == common.CFDModeFlags.TargetCompare()
our assumption that target compare is inly relevant to SMB, right?

2023-04-16 05:58 UTC, aymanjarrousms approved these changes

2023-04-16 06:14 UTC, shyaler commented on cmd/syncComparator.go
> +	isTargetCompare := f.cfdMode == common.CFDModeFlags.TargetCompare()
currently in storage mover scope yes

2023-04-16 07:11 UTC, aymanjarrousms submitted a review, later dismissed

2023-04-16 08:38 UTC, shmuelberezin commented on cmd/zc_traverser_file.go
> +	isDirectoryEndMarke bool
typo: isDirectoryEndMarke -> isDirectoryEndMarker

2023-04-16 08:38 UTC, shmuelberezin requested changes

2023-04-16 08:38 UTC, shmuelberezin commented on cmd/syncComparator.go
>  	// TODO: We need to take care cfdMode == TargetCompare, as for it finalizer will be true. It cause each folder properties updation.
update this comment

2023-04-17 12:13 UTC, shmuelberezin approved these changes

2023-04-17 12:14 UTC, merged