use TreeCrawler with orderedTqueue in fileTraverser in case of sync and target traverser
shyaler/azure-storage-azcopy pull request #16
Opened 2023-04-17 13:51 UTC by shyaler

In case of sync and target traverser -> change the file traverser to work with the source channel (ordered tqueue)
in this case the target traverser is listening to the tqueue channel - and proccess the folder only after the source provide them, in order to compare them.
in enumerate one dir function: 
in case of sync and target file traverser, the enumeation output should be in the format of StoredObject,
enqueue folders that doesnt exist in the target, to be compared with the source in order to copy them

2023-04-17 14:27 UTC, aymanjarrousms commented on cmd/zc_traverser_file.go
> +		dirUrl := dir.(string)
I don't understand this line

2023-04-18 08:13 UTC, shyaler commented on cmd/zc_traverser_file.go
> +		dirUrl := dir.(string)
In the sync we are now getting directories both from the source traverser to enumearates on. so we dont get a full directory url  - but just relative path. so we need to build the full url

2023-04-18 12:12 UTC, shyaler commented on cmd/zc_traverser_file.go
> +					enqueueOutput(output, err)
check this code

2023-04-20 08:57 UTC, shmuelberezin requested changes

2023-04-20 08:57 UTC, shmuelberezin commented on cmd/zc_traverser_file.go
> +	if !isTargetSync {
Please add a comment why we skip processing the root folder in target sync (It will be processed when it's dequeued from orderedTqueue in target sync traversing)

2023-04-20 08:57 UTC, shmuelberezin commented on cmd/zc_traverser_file.go
> +		if dirUrl != "" && !strings.HasPrefix(dirUrl, common.AZCOPY_PATH_SEPARATOR_STRING) {
Maybe rename to relativePath?

2023-04-20 08:57 UTC, shmuelberezin commented on cmd/zc_traverser_file.go
> +		currentDirURL := azfile.NewDirectoryURL(fileUrl, t.p)
The regular enququeDir still adds an azfile.DirectoryURL, so I suggest wrapping these lines with if-else or a switch to be done only when isTargetSync.

2023-04-20 08:57 UTC, shmuelberezin commented on cmd/zc_traverser_file.go
>  				}
I don't think that enqueueOutput of the child directory is related to if t.recursive.

2023-04-20 08:57 UTC, shmuelberezin commented on cmd/zc_traverser_file.go
> +					enqueueOutput(output, err)
I'm not sure that it should be skipped when isTargetSync. Let's discuss this case.

2023-04-23 08:29 UTC, shyaler commented on cmd/zc_traverser_file.go
> +					enqueueOutput(output, err)
discussed offline, the directory will be enumerated driven by the source (unsatarted dirs)

2023-04-23 09:12 UTC, shmuelberezin requested changes

2023-04-23 09:12 UTC, shmuelberezin commented on cmd/zc_traverser_file.go
> +				false, /*isRoot*/
In TargetSync this could be the root folder, so maybe there is a need to check it here for the idnoe enforcement check?

2023-04-23 09:12 UTC, shmuelberezin commented on cmd/zc_traverser_file.go
> +					storedObject := StoredObject{
Also here, in TargetSync this could be the root folder, so maybe there is a need to check it here for the idnoe enforcement check?

2023-04-23 09:15 UTC, shmuelberezin commented on cmd/zc_traverser_file.go
> +		if isTargetSync {
Maybe isSync for not breaking the file traverser as a sync source traverser?

2023-04-23 11:02 UTC, shyaler commented on cmd/zc_traverser_file.go
> +					storedObject := StoredObject{
since the folder doesn't exist in the target, we will not have an inode check

2023-04-24 07:29 UTC, shyaler commented on cmd/zc_traverser_file.go
> +		if isTargetSync {
mmm we will still need the inode there..

2023-04-24 07:29 UTC, shyaler commented on cmd/zc_traverser_file.go
> +				false, /*isRoot*/
created a different task to handle it https://msazure.visualstudio.com/One/_workitems/edit/19110607

2023-04-24 11:06 UTC, shmuelberezin approved these changes

2023-04-24 11:18 UTC, merged